// Centralized application state
export const AppState = {
    allRepeaters: [],
    filteredRepeaters: [],
    currentSort: { column: null, direction: 'asc' },
    userLocation: null,
    currentView: 'table',
    lastDataUpdate: null,
    favorites: new Set(),
    map: null,
    mapInitialized: false,
    mapReady: null,
    selectedRepeater: null,
    repeaterLinks: [],
    drawIntertieLinks: false,
    drawOtherLinks: false,
    drawNonValidatedLinks: false,
    nonValidatedLinks: [],
    detailRepeater: null,
};
